{
 "title": "Jitsi",
 "description": "Dashboard for Jitsi Meet Exporter",
 "tags": [ "jitsi" ],
 "time": { "from": "now-1d/d", "to": "now-1d/d" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(jitsi_conferences, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Conferences",
   "type": "stat",
   "description": "The current number of conferences.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jitsi_conferences{pod=~\"$pod.*\"})",
     "legendFormat": "Conferences"
    }
   ]
  },
  {
   "title": "Current Participants",
   "type": "stat",
   "description": "The total number of participants over all JVBs",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(jitsi_participants)", "legendFormat": "Current Participants" }
   ]
  },
  {
   "title": "RTT",
   "type": "stat",
   "description": "An average value (in milliseconds) of the RTT across all streams.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(jitsi_rtt_aggregate{pod=~\"$pod\"})",
     "legendFormat": "RTT"
    }
   ]
  },
  {
   "title": "Bitrate Download",
   "type": "stat",
   "description": "The total incoming bitrate for the video bridge in kilobits per second.",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jitsi_bit_rate_download{pod=~\"$pod\"})",
     "legendFormat": "Bitrate Download"
    }
   ]
  },
  {
   "title": "Video Bridges",
   "type": "stat",
   "description": "The number of currently scaled video bridges. ",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_memory_usage_bytes{container='jitsi',pod=~\"$pod\"})",
     "legendFormat": "Video Bridges"
    }
   ]
  },
  {
   "title": "Biggest Conference",
   "type": "stat",
   "description": "The number of participants in the largest conference currently hosted on the bridge.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jitsi_largest_conference{pod=~\"$pod\"})",
     "legendFormat": "Biggest Conference"
    }
   ]
  },
  {
   "title": "Stress Level",
   "type": "stat",
   "description": "The sum of reported stress level from the total number of video bridges.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jitsi_stress_level) / count(container_memory_usage_bytes{container='jitsi',pod=~\"$pod\"})",
     "legendFormat": "Stress Level"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "stat",
   "description": "An average value (in milliseconds) of the jitter across all streams.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(jitsi_jitter_aggregate{pod=~\"$pod.*\"})",
     "legendFormat": "Jitter"
    }
   ]
  },
  {
   "title": "Bitrate Upload",
   "type": "stat",
   "description": "The total outgoing bitrate for the video bridge in kilobits per second.",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jitsi_bit_rate_upload{pod=~\"$pod\"})",
     "legendFormat": "Bitrate Upload"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "description": "The number of Java threads that the video bridge is using.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jitsi_threads{pod=~\"$pod\"})",
     "legendFormat": "Threads"
    }
   ]
  },
  { "title": "Histogram", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Conferences",
   "type": "graph",
   "description": "The current number of conferences.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jitsi_conferences{pod=~\"$pod.*\"}",
     "legendFormat": "{{pod}}"
    },
    { "expr": "sum(jitsi_conferences)", "legendFormat": "Sum" }
   ]
  },
  {
   "title": "Participants",
   "type": "graph",
   "description": "The current number of participants.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jitsi_participants{pod=~\"$pod.*\"}",
     "legendFormat": "{{pod}}"
    },
    { "expr": "sum(jitsi_participants)", "legendFormat": "Sum" }
   ]
  },
  {
   "title": "Channels",
   "type": "graph",
   "description": "The current number of sent video and audio channels.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jitsi_endpoints_sending_audio)",
     "legendFormat": "audiochannels"
    },
    {
     "expr": "sum(jitsi_endpoints_sending_video)",
     "legendFormat": "videochannels"
    }
   ]
  },
  { "title": "JVB Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Bitrate",
   "type": "graph",
   "description": "The total incoming/outgoing bitrate for the video bridge in kilobits per second.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "jitsi_bit_rate_download{pod=~\"$pod.*\"}",
     "legendFormat": "{{pod}} - download"
    },
    {
     "expr": "jitsi_bit_rate_upload{pod=~\"$pod.*\"}*(-1)",
     "legendFormat": "{{pod}} - upload"
    }
   ]
  },
  {
   "title": "Package Rate",
   "type": "graph",
   "description": " The total incoming/outgoing packet rate for the video bridge in packets per second.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jitsi_packet_rate_download{pod=~\"$pod.*\"}",
     "legendFormat": "{{pod}} - download"
    },
    {
     "expr": "jitsi_packet_rate_upload{pod=~\"$pod.*\"}*(-1)",
     "legendFormat": "{{pod}} - upload"
    }
   ]
  },
  {
   "title": "Jitter Aggregate",
   "type": "graph",
   "description": "Experimental. An average value (in milliseconds) of the jitter calculated for incoming and outgoing streams. This hasn't been tested and it is currently not known whether the values are correct or not.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "jitsi_jitter_aggregate{pod=~\"$pod.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RTT",
   "type": "graph",
   "description": "An average value (in milliseconds) of the RTT across all streams.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "jitsi_rtt_aggregate{pod=~\"$pod.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Transmitted Bytes Rate per JVB per 5 min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\"}[5m])*100) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Lost RTP packets",
   "type": "graph",
   "description": "The fraction of lost incoming RTP packets. This is based on RTP sequence numbers and is relatively accurate.\nThe fraction of lost outgoing RTP packets. This is based on incoming RTCP Receiver Reports, and an attempt to subtract the fraction of packets that were not sent (i.e. were lost before they reached the bridge). Further, this is averaged over all streams of all users as opposed to all packets, so it is not correctly weighted. This is not accurate, but may be a useful metric nonetheless.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jitsi_incoming_loss{pod=~\"$pod.*\"}",
     "legendFormat": "download"
    },
    {
     "expr": "jitsi_outgoing_loss{pod=~\"$pod.*\"}",
     "legendFormat": "upload"
    }
   ]
  },
  {
   "title": "Sent/Received Websockets",
   "type": "graph",
   "description": "The total number messages sent/received through COLIBRI web sockets.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jitsi_total_colibri_web_socket_messages_received{pod=~\"$pod.*\"}[$__rate_interval])",
     "legendFormat": "{{pod}} - received"
    },
    {
     "expr": "rate(jitsi_total_colibri_web_socket_messages_sent{pod=~\"$pod.*\"}[$__rate_interval])*(-1)",
     "legendFormat": "{{pod}} - sent"
    }
   ]
  },
  {
   "title": "Coturn-Data",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=\"coturn-0\"}[$__rate_interval]))",
     "legendFormat": "receive-coturn-1"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=\"coturn-0\"}[$__rate_interval])*(-1))",
     "legendFormat": "transmit-coturn-1"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=\"coturn-1\"}[$__rate_interval]))",
     "legendFormat": "receive-coturn-2"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=\"coturn-1\"}[$__rate_interval])*(-1))",
     "legendFormat": "transmit-coturn-2"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=\"coturn-2\"}[$__rate_interval]))",
     "legendFormat": "receive-coturn-3"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=\"coturn-2\"}[$__rate_interval])*(-1))",
     "legendFormat": "transmit-coturn-3"
    }
   ]
  },
  {
   "title": "CPU Usage of JVBs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container='jitsi',pod=~\"$pod\"}[$__rate_interval])) by (pod) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage of JVBs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container='jitsi',pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of Running JVB Pods",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(container_memory_usage_bytes{container='jitsi',pod=~\"$pod\"})",
     "legendFormat": "number of pods"
    }
   ]
  },
  {
   "title": "Octo transfer bytes",
   "type": "graph",
   "description": "The current data rate of Octo-Channels",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(jitsi_total_bytes_received_octo{pod=~\"$pod.*\"}[$__rate_interval])",
     "legendFormat": "Octo received"
    },
    {
     "expr": "rate(jitsi_total_bytes_sent_octo{pod=~\"$pod.*\"}[$__rate_interval])*(-1)",
     "legendFormat": "Octo sent"
    }
   ]
  },
  {
   "title": "(Partially) Failed Conferences",
   "type": "graph",
   "description": "The rate of (partially) failed conferences on the bridge. A conference is marked as partially failed when some of its channels has failed. A channel is marked as failed if it had no payload activity.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jitsi_total_partially_failed_conferences{pod=~\"$pod.*\"}[$__rate_interval])",
     "legendFormat": "partially failed conferences"
    },
    {
     "expr": "rate(jitsi_total_failed_conferences{pod=~\"$pod.*\"}[$__rate_interval])",
     "legendFormat": "failed conferences"
    }
   ]
  },
  {
   "title": "Loss-controlled participant-seconds",
   "type": "graph",
   "description": "The rate of participant-seconds that are loss-controlled.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jitsi_total_loss_controlled_participant_seconds[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Loss-limited participant-seconds",
   "type": "graph",
   "description": "The rate of loss limited seconds of participants in all conferences.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jitsi_total_loss_limited_participant_seconds[$__rate_interval])",
     "legendFormat": "failed conferences"
    }
   ]
  },
  {
   "title": "Loss-degraded participant-seconds",
   "type": "graph",
   "description": "The rate of participant-seconds that are loss-degraded.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jitsi_total_loss_degraded_participant_seconds{pod=~\"$pod.*\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}