name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Update Release
    runs-on: ubuntu-20.04
    steps:
      - name: Publish Release
        uses: release-drafter/release-drafter@v6
        with:
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
